name: Matrix demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [14, 16, 18]
                os: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 18
                      os: macos-latest
                exclude:
                    - node-version: 14
                      os: windows-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get the code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
                
